model:
  name: "mrm8488/bert-tiny-finetuned-fake-news-detection"
  max_length: 512

factcheck:
  api_key: null  # Set your Google Fact Check Tools API key here
  enabled: false

scoring:
  weights:
    model_confidence: 0.5
    fact_check_evidence: 0.3
    source_reputation: 0.2

domain_reputation:
  file: "domain_reputation.json"

app:
  host: "0.0.0.0"
  port: 8000
  debug: true